export const ActionTypes = {
    CREATE_FOLDER: 'CREATE_FOLDER',
    SELECT_FOLDER: 'SELECT_FOLDER',
    UPDATE_FOLDER: "UPDATE_FOLDER",
    REMOVE_SELECTED_FOLDER: 'REMOVE_SELECTED_FOLDER',
    SET_CHILD_FOLDERS: "SET_CHILD_FOLDERS",
    SET_CHILD_FILES: "SET_CHILD_FILES"
};